spinnaker/spin

.travis.yml

**Don't merge yet, testing the TravisCI builds.**

chore(travisci): Adds build script for TravisCI.

---

.travis.yml
command/meta.go
command/pipelines/pipeline_list.go
command/pipelines/pipeline_list_test.go
command/pipelines/pipeline_save.go
command/pipelines/pipeline_save_test.go

Also fixes a few small bugs found in writing the tests :)

testing(pipelines): Adds missing pipeline unit tests.

---

command/applications/application_delete.go
command/applications/application_get.go
command/applications/application_list.go
command/applications/application_save.go
command/meta.go
command/pipelines/pipeline_delete.go
command/pipelines/pipeline_execute.go
command/pipelines/pipeline_get.go
command/pipelines/pipeline_list.go
command/pipelines/pipeline_save.go
config/auth/authconfig.go
config/auth/oauth2/config.go
config/example.yaml

feat(auth/oauth2): Support for OAuth2 as an authentication method.

---

command/meta.go
config/auth/basic/config.go

adds support for basic auth for users using ldap based authentication

feat(auth/basic): add support for basic auth

---

command/applications/application_save.go
command/applications/application_save_test.go
command/pipelines/pipeline_save.go

feat(app): Support saving app from file and stdin.

---

command/applications/application_save.go
command/applications/application_save_test.go
command/pipelines/pipeline_execute.go

Depends on https://github.com/spinnaker/orca/pull/2387.

feat(apps): Wait on task completion to report success.

---

command/applications/application_save.go
command/pipelines/pipeline_execute.go
command/pipelines/pipeline_save.go
util/json_reader.go

Also a small refactor to reduce repeated json parsing code from file/stdin. Closes https://github.com/spinnaker/spinnaker/issues/3216. @MrTrustor FYI.

Execute params

---

command/applications/application_get.go
command/applications/application_list.go
command/cli_ui.go
command/meta.go
command/output/output.go
command/pipelines/pipeline_get.go
command/pipelines/pipeline_list.go

Needs a doc update with a link to https://kubernetes.io/docs/reference/kubectl/jsonpath/. @MrTrustor FYI.

refactor(output): Refactors json output.

---

command/meta.go

Closes https://github.com/spinnaker/spinnaker/issues/3129. @wheleph FYI.

feat(auth): Adds code verifier to oauth2 exchange.

---

config/example.yaml

https://github.com/spinnaker/spin/pull/62 added functionality but for the 1.10 release but did not document how to use the new functionality. This just provides the example (provided in the PR) to the repo.

feat(config): Include example for Overriding the Gate Endpoint

---

cmd/gateclient/client.go

Gate calls were subtly broken due to OAuth2 redirects.
GET calls were traversing the redirects fine, but POST
calls would be turned into GETs with no body, which
the Gate Controllers fail on. Now, when we resolve the
oauth2 token we immediately establish a session for the life
of the spin command so all calls are authenticated.

fix(oauth2): Fixes API calls using OAuth2.

---

cmd/pipeline-template/list.go
cmd/pipeline-template/save.go
cmd/pipeline/save.go

Small typo fixes in a few other files as well.

fix(pipelines): Fixes saving templated pipelines.

---

cmd/pipeline-template/plan.go

fix(pipeline-templates): Update plan command for change in v2 template

---

gateapi/api/swagger.yaml
gateapi/api_client.go
gateapi/project_controller_api.go

Related to https://github.com/spinnaker/spinnaker/issues/3787

chore(swagger): Added gate-web /projects/* support.

---

cmd/gateclient/client.go
cmd/pipeline/execute.go
cmd/root.go
config/auth/iap/config.go
config/auth/iap/oauth.go
config/auth/iap/oauth_template.go
config/auth/iap/user_iap_auth_helper.go
config/auth/iap/user_iap_auth_helper_test.go
config/example.yaml
util/execcmd/execcmd_darwin.go
util/execcmd/execcmd_linux.go
util/execcmd/execcmd_windows.go

add IAP support for auth, add support for Spinnaker instances which has IAP enabled for auth

feat(google iap): add iap support for user login

---

.gitattributes
.gitignore
release.sh

Also includes .git* changes to assist with development on Windows.

feat(windows): Build Windows executable on release

---

cmd/pipeline-template/get.go
cmd/pipeline-template/get_test.go

Also fails if id is not present.

fix(pipeline-template): Accept STDIN in save cmd.

---

cmd/gateclient/client.go

@MrTrustor PTAL and test run as well please.

feat(client): Checks for Gate liveness before executing cmd.

---

cmd/gateclient/client.go
config/auth/authconfig.go
config/auth/ldap/config.go

Provides authentication for gate deployments with ldap.
This will also enable LDAP for the terraform provider (https://github.com/armory-io/terraform-provider-spinnaker).

feat(gateclient): Add LDAP Authentication

---

CONTRIBUTING.md
README.md

Adds a contributing doc with details on how the project uses Swagger and how to update the api client lib

docs(contributing): Contributing doc and info on gate api

---

build.sh
gateapi/git_push.sh
release.sh
travisBuild.sh

This pull request is the result of a code review for the spin project, where in part the author ran the shellcheck linter against all shell script files to identify potential problems.
The commits which make up this pull request have been tested locally, and are believed to be low risk to the project.
The changes made are intended to improve the reliability of the changed shell scripts.  No new features are added.

Linter fixes for shell scripts

---

config/auth/authconfig.go
config/auth/basic/config.go
config/auth/googleserviceaccount/config.go
config/auth/iap/config.go
config/auth/iap/service_account_auth_helper.go
config/auth/iap/user_iap_auth_helper.go
config/auth/ldap/config.go
config/auth/oauth2/config.go
config/auth/x509/config.go
config/config.go
config/example.yaml

This is another trivial pull request as I develop an understanding of the code base.  Here we make some linter fixes and other simple changes.
* Changed .go file formatting to satisfy linter/goLand IDE.
* Aligned structs for more pleasing visual formatting.
* Linter fixes for example.yaml.
* Changed several Config structs from redundant names such as OauthConfig, since these structs are in a package and can be referenced as oauth2.config, etc.  This will help keep the code clean and easier to read.
--Sam

fix(config/*): linter fixes for the config/* files.

---

util/cli_ui.go

Currently passing something like `"jsonpath={[*]..id},{[*]..application}"` to
--output only returns the id. This change returns all the matches instead of
just the first one.
Example:
Given the pipeline list json in pipelineListJson, we would currently return
`"pipeline1"` if the user passed `"jsonpath={[*]..id},{[*]..application}"` to --output
With this change we would print `"pipeline1,app"` instead, as that's how kubectl
would print it.
When you have multiple pipelines the output would be:
`"pipeline1 pipeline2 pipeline3,app app app"`

fix(jsonpath): Return all matches from jsonpath, not just first

---

cmd/project/list.go
cmd/project/project.go

`spin project list` will list all projects

ability to list all projects

---

cmd/gateclient/client.go

Opening PR to understand why tests fail in build -- this fixes accidental merge via https://github.com/spinnaker/spin/pull/271

perf(updating spin config): spin config gets rechecked multiple times

---

cmd/pipeline/save.go

This incorporates https://github.com/spinnaker/spin/pull/257 to fix https://github.com/spinnaker/spinnaker/issues/5900

fix(pipelineSave): can create a new pipeline in 1.21.x

---

cmd/gateclient/client.go

fix(gateclient): typo receiver

---

cmd/project/delete.go
cmd/project/project.go

To round out https://github.com/spinnaker/spinnaker/issues/3651 this PR adds the ability to delete a project. `spin project delete --name <project name>` will delete the given project.

feat(deleteProject): add ability to delete a project

---

cmd/pipeline/execute.go

adds an option to specify multiple key=value parameters instead of using
a parameter file. the default behavior is kept the same but if the user
passes `-p` instead, it will parse the arguments as key/value pairs.

feat(execute): add individual parameter option

---

cmd/pipeline/save.go

As stated here: https://github.com/spinnaker/spinnaker/issues/5945#issuecomment-665805654
> custom pipeline config IDs are deliberately allowed.
This replaces #288

feat(pipeline/save): don't prevent pipeline ID collisions

---

cmd/pipeline/save.go

fix(pipeline/save): save pipeline works for 1.21.x 

---

cmd/account/account.go
cmd/account/whoami.go
cmd/account/whoami_test.go
go.sum

Adds access to [/auth/user](https://spinnaker.io/docs/reference/api/docs.html#api-Authcontroller-userUsingGET) to cli via `spin account whoami`.
Closes https://github.com/spinnaker/spinnaker/issues/6439

feat(account): Add whoami command
