release.sh

Our travisCI GCP page said to use the curl/bash solution... seems to be out of date

chore(release): non-interactive gcloud install

---

command/meta.go

Added flag to ignore certificate validation errors for those using SSL certs that aren't in a CA.

feat (auth/ssl): add flag to ignore certificate validation errors

---

command/meta.go

@jtk54  This PR fixes #1 by doing TrimSpace to the pasted state token.

fix(meta): TrimSpace before returning OAuth2 state token read from STDIN

---

README.md

The installation instructions is outdated here, removing it and pointing to the spinnaker.io documentation.

docs(installation): Point to documentation on spinnaker.io

---

command/meta.go

There is a issue when running on alpine linux. It will error when trying to find the users home directory:
```
Could not read current user from environment, failing.
user: Current not implemented on linux/amd64
```
This PR will first try to use user.Current, if that fails then it will attempt to get the home directory from the environment.

feat(build): Fixing user home bug

---

command/meta.go
config/config.go

make `gate-endpoint` configurable via config file. the CLI flag takes
precedence over the config file.

feat(config): gate endpoint configurable

---

travisBuild.sh

Saw this in https://travis-ci.org/spinnaker/spin/builds/454077918, we have `spin` integrated into the buildtools so the release part of the metal travis script is unnecessary.

chore(travisCI): Removes release from travisCI builds.

---

cmd/application/get.go
cmd/application/list.go
cmd/gateclient/client.go
cmd/root.go

Clean-up refactor ahead of planned expansion for IAP-related changes. Also cleans up the double error printing from Cobra.

refactor(gateclient): Cleanup around NewGateClient.

---

cmd/pipeline/save.go
cmd/pipeline/save_test.go

Helps support pipeline templates and was overly strict anyway
since Orca generates a UUID anyway and the other pipeline commands
operate on name/app pair.

fix(pipeline): Removes constraint requiring id field.

---

cmd/application/get.go
cmd/application/list.go

Also changes the default unexpanded output to be identical to the _input_ of the `app save` command.

feat(app): Adds expand flag for app get.

---

cmd/application/delete.go
cmd/application/get.go

Also fixes incorrect flag help text in `app get`.

fix(app): Fails on deleting non-existent app.

---

cmd/application/save.go
cmd/pipeline-template/plan.go
cmd/pipeline-template/save.go
cmd/pipeline/execute.go
cmd/pipeline/save.go
util/json_reader.go

Previously the command would fail if there was no file input from either a flag or STDIN, which was a regression.

fix(app): Fixes specifying apps with flags only.

---

config/auth/iap/user_iap_auth_helper.go

Without this fix, the error is still propagated even though the user has followed the displayed link.

fix(iap): Clear err variable after printing link.

---

cmd/pipeline/execute.go
util/json_reader.go

The input artifacts file must take the form of:
```json
{
"artifacts": [
{ <artifact 1> },
...
{ <artifact N> }
]
}
```

feat(pipeline/exec): Support passing artifacts when executing pipelines.

---

cmd/gateclient/client.go

from TCP dial. Previous fix [here](https://github.com/spinnaker/spin/pull/152) was over-restrictive. @MrTrustor FYI.

fix(gateclient): Converts reachable host check to http GET.

---

cmd/gateclient/client.go

Per comment https://github.com/spinnaker/spin/pull/164#issuecomment-484340150
`gofmt` also tweaked a couple of lines here.

fix(gateapi): close body after http.Get to avoid leaking resources

---

cmd/gateclient/client.go

The Gate liveness check needs rethought since it doesn't handle authentication cases and is breaking for forwarded ports. Reverting for now.

fix(client): Reverts Gate liveness check.

---

cmd/application/get_test.go
cmd/gateclient/client.go
cmd/pipeline-template/get_test.go
cmd/pipeline/execution/get_test.go
cmd/pipeline/get_test.go
cmd/root.go

This PR provides functionality requested in issue #180
A new flag has been added for default-headers which accepts a comma separated list of key value pairs of headers that will be set as defaults on the gate client to be sent through on each request to the gate endpoint.
As mentioned in issue #180 the purpose of this was to allow passing custom headers that may be required if the gate endpoint is only exposed via some sort of api gateway.
`./spin application list --gate-endpoint=https://myapigateway.test.com/gate --default-headers=X-Api-Service-Key=secrettoken,secondHeaderKey=value`
this is the output from running the go tests:
```
?   	github.com/spinnaker/spin	[no test files]
?   	github.com/spinnaker/spin/cmd	[no test files]
ok  	github.com/spinnaker/spin/cmd/application	0.379s
? …
```

feat(gateclient): add default-headers flag for gate client requests

---

Dockerfile
Dockerfile.slim
release.sh

This allows a complete build using Docker, or building an image from an already compiled copy using using Dockerfile.slim.
This partially addresses https://github.com/spinnaker/spinnaker/issues/4531. Further modifications are probably required to https://github.com/spinnaker/spinnaker/blob/master/dev/buildtool/spin_commands.py to address release publication.

feat(docker): Add Dockerfile for building Docker images

---

cmd/application/delete_test.go
cmd/application/list_test.go
cmd/application/save_test.go
cmd/pipeline-template/delete_test.go
cmd/pipeline-template/get_test.go
cmd/pipeline-template/list_test.go
cmd/pipeline-template/plan_test.go
cmd/pipeline-template/save_test.go
cmd/pipeline/execute_test.go
cmd/pipeline/execution/cancel_test.go
cmd/pipeline/execution/get_test.go
cmd/pipeline/execution/list_test.go
cmd/pipeline/get_test.go
cmd/pipeline/list_test.go
cmd/pipeline/save_test.go
util/test_helpers.go

First question is are the tests currently running in Travis? I was unable to run the tests successfully (for any tests targeting a test server representing Gate) on a clean clone. Assuming I don't have something wrong with my local, it looks like none of the test servers were handling a route for `/version` -- https://github.com/spinnaker/spin/blob/master/cmd/gateclient/client.go#L167-L171
This change adds handling for that (~rather verbosely but would like the get the tests passing first before I work on the changes I had in mind)~. These changes allowed for me to run the tests locally on a clean branch. I can follow-up to abstract the configuring of the test servers as needed.
If I'm correct that the tests are not running against PRs (quick glance at a recent PR, I didn't see a status …

fix(cmd): handle calls to version endpoint in tests

---

cmd/pipeline/execute.go

Checking for exactly one RUNNING execution isn't reliable for a few
of reasons:
- for a pipeline that allows multiple simultaneous executions, there can
be more than one running at a time
- for a pipeline that doesn't allow multiple executions, there is no
check that the returned execution is the one that was just triggered,
instead of one that was executing previously
- if a pipeline starts and finishes in between the retries, while the
check is sleeping, then it will report failure despite having succeeded

fix(cmd): Remove flaky checks for successful executions

---

CONTRIBUTING.md

Go versions less than 1.12 are deprecated so removing setup instructions for it. I also upgraded the build to use 1.13.x in response to [this change](https://github.com/golang/go/issues/34742).

docs(contributing): Remove setup for < go version 12

---

config/example.yaml

The link to ssl was broken and I guess it should target https://www.spinnaker.io/setup/security/ssl/ instead.
I've opened a [PR](https://github.com/spinnaker/spinnaker.github.io/pull/1596) into the spinnaker documentation web site as well.

docs(config/example): Update link reference to "ssl"

---

cmd/pipeline/save.go
cmd/pipeline/save_test.go

A fix for https://github.com/spinnaker/spinnaker/issues/5092, makes `spin` correctly return a non-zero exit code and outputs error to stderr. 
Additonally, added a test for this case, simulating non-authorized write attempt.

fix(cmd): Fix pipeline save error detection

---

.travis.yml
cmd/account/account.go
cmd/account/get.go
cmd/account/get_test.go
cmd/account/list.go
cmd/account/list_test.go
cmd/root.go

The `account` subcommand has `get` and `list` commands. Useful for getting all available deployment targets when generating pipelines.

feat(cmd): add `account` sub command for querying configured accounts

---

.github/workflows/ci.yml

Followed basic layout from https://github.com/mvdan/github-actions-golang and pulled commands from prexisting Travis CI steps.

chore(builds): Adds GHActions CI for PRs, master, and release branches.

---

cmd/output/output.go

cc @karlkfi @sikevux
Revert the change in #241. This isn't a clean revert because #243 restructured things so much, but this puts things back the way they were.
@karlkfi noticed in #243 that if your jsonpath expression returns a complex (non-string) type, instead of JSON, it outputs a bunch of golang-formatted strings, like `map[EXECUTE:[admin-group] READ:[admin-group user-group] WRITE:[admin-group]]`.

fix(jsonpath): revert jsonpath change, so we output json again

---

cmd/gateclient/client.go
config/auth/authconfig.go
go.mod
go.sum

Hey all, I am working on a [spinnaker managed delivery tool](https://github.com/Spinnaker/md-lib-go) where I was hoping to reuse the ~/.spin/config file and authentication code that is in this project.  This PR tries to untangle the http client authentication code from the cli/flags setup so that it can be used independently.
I don't believe there are any functional changes for the `spin` project, just moving some of the code around and creating a few more exported functions.
This is currently how I am using this code:
https://github.com/spinnaker/md-lib-go/blob/master/cmd/spinmd/main.go#L41
I am open to any suggestions.  Thanks!

refactor base gate http client to be usable outside spin cli

---

cmd/account/get_test.go
go.mod
go.sum

gateapi 1.21.x autogenerated code from swagger will return json payload with the keys sorted differently. This is to address that issue

test(account/get): use jsondiff to compare responses

---

cmd/project/get.go
cmd/project/project.go

This depends on PR https://github.com/spinnaker/spin/pull/259 -> the original get.go was for getting pipelines and confusing as it didn't match the subcommand `get-pipelines`. PR 259 corrects that and this PR adds the ability to get a single project's config.

(feat) Add get project command

---

cmd/project/project.go
cmd/project/save.go
cmd/project/save_test.go
util/json_test_files/example_project.json

`spin project save --file <filename` will save a project. Setting just the name and email flags will also create a project with nothing in it. Like the `spin application save` command if you pass in a file with the name or email flags, the value passed via the flags will override what's in the file.
This PR also introduces a test for the save function, noting that all other tests for projects are missing and will be added in near future.
The corresponding sponnet changes are in this PR: https://github.com/spinnaker/sponnet/pull/11

Add save project command

---

cmd/gateclient/client.go

This PR touches on: https://github.com/spinnaker/spinnaker/issues/5913 which sparked the following PRs to open: https://github.com/spinnaker/spin/pull/268/files https://github.com/spinnaker/spin/pull/269 and https://github.com/spinnaker/spin/pull/263 which are all duplicates of each other. This PR has the same fix but also skips rechecking methods that weren't in the config originally.
Old behavior: If you didn't have LDAP set but cached your oauth token, your config got updated to set LDAP to null in the config. This cleans that up as well sets the appropriate update message for the other methods updates like GSA token.

perf(updating spin config): spin config gets rechecked multiple times

---

cmd/gateclient/client.go
config/example.yaml

Documentation for clarity around https://github.com/spinnaker/spinnaker/issues/5913 and how to set a cached token for oauth to the spin CLI correctly, as well as a link update to the providers in the example config

doc(auth config): explaining how to set the auth config properly and code walk-through comments

---

cmd/pipeline/save.go

With latest spinnaker version The ApplicationControllerApi.GetPipelineConfigUsingGET returns 404 for non-existing pipeline.
Updated pipeline save to check for status http.StatusOK and foundPipeline both.

fix(pipelineSave) Fixed issue for pipeline save with spinnaker 1.21.x

---

cmd/pipeline/pipeline.go
cmd/pipeline/update.go

This gives users the ability to update pipelines without passing in the entire json but instead commonly used flags. For starters, the command gives users the ability to enable or disable a pipeline via the following:
`spin pipeline update --application <application name> --name <pipeline name> --enabled`
or `spin pipeline update --application <application name> --name <pipeline name> --disabled`
spin will return an error if a user tries to pass in both flags. Future work would include being able to easily rename or lock pipelines (think the global configure menu for individual pipelines in the UI).

feat(updatePipeline): ability to disable and enable pipelines easily

---

cmd/gateclient/client.go
go.mod
go.sum
util/filepath.go

Now that Go 1.12 provides `os.UserHomeDir`, this PR uses it instead of [mitchellh/go-homedir](https://github.com/mitchellh/go-homedir). Thanks to this, we can reduce third-party dependency.
- https://golang.org/doc/go1.12#os

chore(gateclient): use os.UserHomeDir instead of mitchellh/go-homedir

---

cmd/canary/canary-config/delete.go
cmd/canary/canary-config/get.go
cmd/canary/canary-config/list.go
cmd/canary/canary-config/retro.go
cmd/pipeline-template/delete.go
cmd/pipeline-template/get.go
cmd/pipeline-template/list.go
cmd/pipeline-template/plan.go
cmd/pipeline-template/use_test.go
cmd/pipeline/delete.go
cmd/pipeline/execute.go
cmd/pipeline/execution/cancel.go
cmd/pipeline/execution/get.go
cmd/pipeline/execution/list.go
cmd/pipeline/execution/list_test.go
cmd/pipeline/get.go
cmd/pipeline/list.go
cmd/pipeline/save_test.go
cmd/project/save_test.go
cmd/root.go
config/auth/iap/config.go
config/auth/iap/oauth.go
gateapi/api_client.go
gateapi/api_response.go
util/execcmd/execcmd_linux.go
util/execcmd/execcmd_windows.go

This PR fixes the format by running `gofmt -w -s .` and `goimports -w -local github.com/spinnaker/spin .` and manually updating some of them to keep the codebase consistent and follow the convention.

fix(format): fix format with gofmt and goimports

---

.golangci.yml

the code in `/gateapi` is autogenerated by swagger. There's not a really good reason to enforce any kind of linting in there.

feat(golang-cli): ignore swagger generated code in gateapi/

---

cmd/application/get_test.go
cmd/output/output_test.go

This change adds tests to prevent unintentional breakage related to
output of non-primitive jsonpath outputs.
The changes made in https://github.com/spinnaker/spin/pull/241 do not
pass these tests, as they return Go-syntax.
Updating client-go to v0.19.0-rc.2 that contains the fix for printing
JSON still does not pass the tests as the output would be encapsulated
in `[]`

test(jsonpath): add tests for non-primitives

---

cmd/pipeline-template/save.go

See issue: https://github.com/spinnaker/spinnaker/issues/6008
Recent changes to pipeline template saving did not take into account saving existing pipeline templates and will return an error without the status check fixed.

fix(pipelineTemplateSave): fix returning error on existing pipeline template saving

---

cmd/pipeline-template/save_test.go

This is to fix the test for the issues mentioned in: https://github.com/spinnaker/spin/pull/298
This addresses github issues https://github.com/spinnaker/spinnaker/issues/6008 and part of https://github.com/spinnaker/spinnaker/issues/6003#issuecomment-685791703
I've confirmed that the test fails properly without the fix in PR 298 and passes correctly with the fix in.

fix(pipelineTemplateSave): fix tests for saving pipeline template

---

.github/workflows/ci.yml

Upgraded some versions in GitHub Actions workflows:
- https://github.com/actions/cache/releases/tag/v2
- https://github.com/actions/setup-go/releases/tag/v2
- https://github.com/golangci/golangci-lint-action/releases/tag/v2
- https://github.com/golangci/golangci-lint/releases/tag/v1.32.2

chose(ci): Upgrade versions in github actions workflows

---

.github/workflows/ci.yml
go.mod

Upgraded the Go version to [`1.15`](https://golang.org/doc/go1.15) and fixed the use of different versions in CI.

chose(dep): Upgrade go version to 1.15

---

cmd/account/get.go
cmd/application/get.go
cmd/canary/canary-config/retro.go
cmd/canary/canary-config/save.go
cmd/gateclient/client.go
cmd/pipeline-template/save.go
cmd/pipeline/save.go
cmd/pipeline/update.go

Removed unnecessary control flows and tidied up some blocks. The behavior wouldn't be changed.
To improve readability and maintainability and allow more users to easily contribute to this project.

refactor(cmd): Clean up value checks

---

cmd/application/application.go
cmd/application/cancel_pipeline.go
cmd/application/cancel_pipelines.go
cmd/application/get_pipelines.go
cmd/application/pipelines.go

This PR adds a pipeline subcommand to `spin application` with 3 subcommand options.
`spin application pipelines get -a <appName>` will list all executions of a pipeline under an application name.
You can narrow this down by passing the status of the pipeline you're looking for. i.e. `-s RUNNING` for example or `-s NOT_STARTED`
If you have the execution ID of a pipeline, you can do:
`spin application pipelines cancel -i <ID>`
If you want to cancel all the pipelines of a particular status under an application and pass a reason for it, you can run:
`spin application pipelines cancel-all -a <appName> -s RUNNING -r "killing zombie executions"`
If you don't pass the status, it will cancel all executions.

feat(applicationPipelines): ability to get execution IDs of pipelines under an application and cancel some or all with reasons

---

CONTRIBUTING.md

As described in [Tag Spin release versions with semver](https://github.com/spinnaker/spinnaker/issues/6189), in Go projects, it's better common to tag the release with semver.
This has many advantages, making it easy to import for users.

Change release tag follow semver

---

config/auth/authconfig.go
config/auth/basic/config.go
config/auth/googleserviceaccount/config.go
config/auth/iap/config.go
config/auth/ldap/config.go
config/auth/oauth2/config.go
config/auth/x509/config.go
config/config.go
config/config_test.go

The sigs.k8s.io/yaml package round-trips YAML through JSON. This means that
without JSON tags on structs, they end up getting the default JSON naming
once marshalled. This change adds JSON tags to all structs, making sure that
the tags after writing the config file back is consistent with what the tags in the source code say.
This PR provides a fix for https://github.com/spinnaker/spinnaker/issues/6434

chore(config): Ensure consistent marshalling/unmarshalling

---

.github/workflows/build.yml
Dockerfile

Following the principle of least privilege we should not run as root
user. There is no need.
Match other Spinnaker services and run as a high user id.
Additional containers generally run the application process as
the entrypoint rather than a shell.
This makes performing commands simpler as we can tack on any arguments
to the end of the image like so:
```
$ docker run --rm -it spin:latest --version
version dev
```
The `VERSION` build arg now defaults to `dev` otherwise an empty VERSION
string overwrites default in Go and results in the `--version` flag
disappearing.

feat(spin): Container improvements, non-root, exec spin, :latest tag

---

cmd/gateclient/client.go

We ran into an issue using an identity provider which did not issue refresh tokens.
Currently the command line tool will fail to authenticate with OAuth2 if using an expired access token and the refresh token is not set. This PR adjusts it to clear the cached credentials if it is expired and there is no refresh token set. The tool will then run the auth routine from the beginning, allowing you to re-log in rather than requiring you edit the spin config file to move forward.

fix(oauth2): ensure refresh token exists before using expired credential

---

.github/dependabot.yml
.github/workflows/build.yml
.github/workflows/pr.yml
.github/workflows/release.yml

Lint action was failing. Bumping versions for various actions seems to fix it.

chore(lint): Bump GitHub Action versions

---

.github/workflows/build.yml
.github/workflows/pr.yml
.github/workflows/release.yml

to avoid warning messages like
Run echo ::set-output name=REPO::${GITHUB_REPOSITORY##*/} Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/ Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

chore(gha): replace deprecated set-output commands

---

cmd/application/delete.go
cmd/application/save.go
cmd/gateclient/client.go
cmd/orca-tasks/task_watcher.go
cmd/orca-tasks/task_watcher_test.go
cmd/project/delete.go
cmd/project/save.go
cmd/root.go
config/config.go
config/config_test.go
config/example.yaml

The old system tried 5 times with an exponential backoff.  The new behavior is based on time, and increases to a maximum of 20 seconds between tries.  It will poll for whatever time is specified on the command line, or in the config file.  Default is 60 seconds, which is the same time the old method would end up using.

Allow polling timeout to be configurable

---

cmd/pipeline-template/save.go
cmd/pipeline-template/save_test.go

Spin ignores tags from pipeline template files, and it causes errors during saving. 
Example of the problem:
1. Create a template with a tag "stable" inside
2. Save it via `spin pt save`. Don't pass the tag to the command, because it already exists in the code
3. Front50 parses the template and finds the tag inside: [code](https://github.com/spinnaker/front50/blob/master/front50-web/src/main/java/com/netflix/spinnaker/front50/controllers/V2PipelineTemplateController.java#L94)
4. Front50 saves the template with the tag
5. Edit the code of the template and save it again
6. Spin tries to find a template in Front50 without tags (because we don't pass the tag via arguments)
7. Spin can't find the template and invokes "create" method instead of "update"
8. Front50 throws an …

fix(pipelineTemplateSave): Take tags from template files

---

cmd/pipeline-template/list.go

When running `spin pipeline-template list` I was receiving an empty list
This is because the path of the request looked like that
```
/gate/v2/pipelineTemplates?scopes=%26%5B%5D
```
the charactere `%26%5B%5D` decodes to `&[]`
Technically we could say the issue comes from `parameterToString` in client.go, and that function should handle receiving a pointer to an array better.
But since this part is generated, here is a fix on the command layer.
To send an array instead of a pointer to an array

fix empty list template response
